name: build-jar
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip -q Mikexxx%20lovely%20lilies.zip
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle Enterprise Network
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.1.1
      - run: gradle build --no-daemon
        working-directory: mod
      - uses: actions/upload-artifact@v4
        with:
          name:Mikexxx_loly_liles.jar path: mod/build/libs/*.jar
